name: Blender Test
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '3.6'

jobs:
  blender-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moguri/setup-blender@v1
        with:
          blender-version: ${{github.event.inputs.version}}
      - run: blender --version
